# syntax = docker/dockerfile:1

ARG RUBY_VERSION=3.1.2
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

ENV RAILS_ENV="development"

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  git \
  libpq-dev \
  libvips \
  pkg-config \
  postgresql-client \
  curl && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN gem update --system 3.5.23 && \
  gem install bundler -v 2.3.26

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
